services:
  - type: web
    name: web_mlbb
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "reflex run --env prod --backend-port $PORT"
    plan: free
    region: oregon
